name: Build & Release
on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          mkdir -p openhd_sys_utils/usr/local/share/openhd_misc
          cp misc/* openhd_sys_utils/usr/local/share/openhd_misc
          mkdir -p openhd_sys_utils/etc/
          cp misc/motd openhd_sys_utils/etc/motd
          mkdir -p openhd_sys_utils/usr/local/bin
          mv *.sh openhd_sys_utils/usr/local/bin
          mkdir -p openhd_sys_utils/etc/system/systemd/
          mv *.service openhd_sys_utils/etc/system/systemd/
          mkdir -p openhd_sys_utils/usr/local/bin/x20/
          mv x20/* openhd_sys_utils/usr/local/bin/x20/
          chmod +x openhd_sys_utils/usr/local/bin/*.sh
          chmod +x openhd_sys_utils/usr/local/bin/x20/runcam_v2/*.sh
          sudo gem install fpm

          VERSION="0.4-$(date +'%m/%d/%Y')"
          VERSION=$(echo "$VERSION" | sed 's/\//-/g')
          fpm -a armhf -s dir -t deb -n openhd_sys_utils -v "$VERSION" -C openhd_sys_utils -p openhd_sys_utils_VERSION_ARCH.deb
          fpm -a arm64 -s dir -t deb -n openhd_sys_utils -v "$VERSION" -C openhd_sys_utils -p openhd_sys_utils_VERSION_ARCH.deb
          
          rm -Rf openhd_sys_utils/usr/local/bin/x20/
          mkdir -p openhd_sys_utils/etc/xdg/autostart/
          mv shortcuts/OpenHD.desktop openhd_sys_utils/etc/xdg/autostart/
          mv shortcuts/QOpenHD2.desktop openhd_sys_utils/etc/xdg/autostart/
          mv shortcuts/steamdeck.desktop openhd_sys_utils/etc/xdg/autostart/
          mv shortcuts/nm-tray-autostart.desktop openhd_sys_utils/etc/xdg/autostart/
          mkdir -p openhd_sys_utils/usr/share/applications/
          cp shortcuts/* openhd_sys_utils/usr/share/applications/
          mkdir -p openhd_sys_utils/home/openhd/Desktop/
          cp shortcuts/*.desktop openhd_sys_utils/home/openhd/Desktop/
          cp shortcuts/*.ico openhd_sys_utils/usr/local/share/openhd_misc/
          chmod a+x  openhd_sys_utils/etc/xdg/autostart/OpenHD.desktop
          chmod a+x  openhd_sys_utils/etc/xdg/autostart/steamdeck.desktop
          chmod a+x  openhd_sys_utils/etc/xdg/autostart/nm-tray-autostart.desktop
          chmod a+x  openhd_sys_utils/etc/xdg/autostart/QOpenHD2.desktop
          fpm -a x86_64 -s dir -t deb -n openhd_sys_utils -v "$VERSION" -C openhd_sys_utils -p openhd_sys_utils_VERSION_ARCH.deb
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            *.deb
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "release"
          distro: "any-distro"
          release: "any-version"
          republish: "true" # needed ONLY if version is not changing
          file: "*armhf.deb"
      - name: Push2
        id: push2
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "release"
          distro: "any-distro"
          release: "any-version"
          republish: "true" # needed ONLY if version is not changing
          file: "*arm64.deb"
      - name: Push3
        id: push3
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "release"
          distro: "any-distro"
          release: "any-version"
          republish: "true" # needed ONLY if version is not changing
          file: "*amd64.deb"